main: "org.ensimag.konohaninja.PluginMain"
version: "1.0"
name: "konoha-no-shinobi"
api-version: "1.17"

depend: [Citizens] 

commands:
   multiclone:
      description: Create multiple clones of the player
      usage: "Usage : /multiclone"
